#!/usr/bin/env python3
#
# gx-signer.py
#
# Take Gaia-X Self-Description (SD) as generated by e.g. openstack-discovery.py and
# - canonicalize
# - hash
# - sign it
# and optionally
# - submit it to compliance.gaia-x.org
#
# (c) Kurt Garloff <garloff@osb-alliance.com>, 6/2022
# SPDX-License: EPL-2.0
import pyld
import hashlib

def canonize_doc(doc):
    "Takes dict and returns a canonized version"
    #doc = dict(doc)
    # Remove old signature
    if "signature" in doc:
        del doc["signature"]
    #doc["@context"] = "https://w3id.org/identity/v1"
    normalized = lyld.jsonld.normalize(doc,
                 {"algorithm": "URDNA2015", "format": "application/n-quads"})
    return normalized

def hash_doc(doc):
    h = hashlib.new("sha256")
    h.update(doc.encode("utf-8"))
    return h.hexdigest()

