"""
Constants used by SCS GX Credential Generator.
"""

DEFAULT_RESOURCE_POLICY = "default: allow intent"
DEFAULT_FIRMWARE_TYPE = "other"
DEFAULT_WATCHDOG_ACTION = "none"

UNIT_MB = "https://qudt.org/vocab/unit/MegaBYTE"
UNIT_GB = "https://qudt.org/vocab/unit/GigaBYTE"
UNIT_GHZ = "https://qudt.org/vocab/unit/GigaHZ"

CONFIG_VM_IMAGE = "vm image"
CONFIG_RESOURCE_POLICY = "resource policy"
CONFIG_LICENSE = "license"
CONFIG_COPYRIGHT = "copyright owner"
CONFIG_OPERATING_SYSTEM = "operating system"
CONFIG_OWN_IMAGES = "own images"
CONFIG_AGGREGATION_OF = "aggregation of"
CONFIG_WALLETS = "wallets"
CONFIG_DEFAULT = "default"
CONFIG_CLOUD_RESOURCES = "cloud resources:"
COMFIG_SOFTWARE = "software resources"
CONFIG_FILESYSTEM_WALLET = "filesystem"
CONFIG_XFSC_WALLET = "xfsc"


CONFIG_OS_ALP = "Alpine Linux"
CONFIG_OS_ARCH = "Arch Linux"
CONFIG_OS_CENTOS = "CentOS Linux"
CONFIG_OS_DEBIAN = "Debian"
CONFIG_OS_FEDORA = "Fedora"
CONFIG_OS_FREEBSD = "FreeBSD"
CONFIG_OS_GENTOO = "Gentoo Linux"
CONFIG_OS_MANDRAKE = "Mandrake Linux"
CONFIG_OS_MANDRIVA = "Mandriva Linux"
CONFIG_OS_MES = "Mandriva Enterprise Server"
CONFIG_OS_MSDOS = "MS-DOS"
CONFIG_OS_NETBSD = "NetBSD"
CONFIG_OS_NOVELL = "Novell Netware"
CONFIG_OS_OPENBSD = "OpenBSD"
CONFIG_OS_SOLARIS = "OpenSolaris"
CONFIG_OS_OPEN_SUSE = "openSUSE"
CONFIG_OS_ROCKY = "Rocky Linux"
CONFIG_OS_RHEL = "Red Hat Enterprise Linux"
CONFIG_OS_SLED = "SUSE Linux Enterprise Desktop"
CONFIG_OS_UBUNTU = "Ubuntu"
CONFIG_OS_WINDOWS = "Microsoft Windows"
CONFIG_OS_CIRROS = "CirrOS"
CONFIG_OS_ALMALINUX = "AlmaLinux"

CONFIG_HV_KVM = "KVM"
CONFIG_HV_QUEMU = "quemu"
CONFIG_HV_XEN = "Xen"
CONFIG_HV_ESXI = "ESXi"
CONFIG_HV_CH = "Cloud Hypervisor"
CONFIG_HV_VMW = "vmware"
CONFIG_HV_HYV = "hyper-v"

CONFIG_FILE = "config/config.yaml"
