# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check Python application

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        # pip install flake8 pytest
        pip install -r test-requirements.txt
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        python3 -m pytest tests --doctest-modules --junitxml=junit/test-results.xml
    
