# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check Python application

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"


permissions:
  contents: read
  pull-requests: write

jobs:
  build-python-app:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r test-requirements.txt
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          python -m pytest --cov --cov-report=xml
          coverage report
        shell: bash

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '90 95'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ !cancelled() && github.event_name == 'pull_request' }}
        with:
          recreate: true
          path:
            code-coverage-results.mdwith:

      - name: Write to Job Summary
        if: ${{ !cancelled() }}
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

