# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint Python

on:
  push:
    paths:
      - '**.py'
      - .github/workflows/lint-python.yml

jobs:
  lint-python-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip3 install flake8
      - run: flake8 --exclude generator/common/gx_schema.py

